# Stage 1: Build the app
FROM node:20-bookworm-slim AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# Stage 2: Serve the app with Nginx
FROM nginx:alpine

# Copy the "dist" folder from the build stage to Nginx's public folder
COPY --from=build /app/dist /usr/share/nginx/html
# Copy custom config to the Nginx config directory
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
