FROM node:20-bookworm-slim

WORKDIR /app

# install python and c++ required to compile libraries like sqlite3
RUN apk add --no-repeat --no-cache make gcc g++ python3

COPY package*.json ./

RUN npm install

COPY main.js ./

EXPOSE 8081

CMD ["node", "main.js"]
