FROM node:20-bookworm-slim

WORKDIR /app

# install python and c++ required to compile libraries like sqlite3
RUN apt-get update && \
    apt-get install -y --no-install-recommends build-essential python3 && \
    rm -rf /var/lib/apt/lists/*

COPY package*.json ./

RUN npm install

COPY main.js ./

EXPOSE 8081

CMD ["node", "main.js"]
